version: '3.4'

services:

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_aws
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=demo
      - AWS_SECRET_ACCESS_KEY=demo
      - EDGE_PORT=4566
      - SERVICES=ssm
    volumes:
      - './localStackSetup.sh:/docker-entrypoint-initaws.d/make-ssm.sh'
    ports:
      - '4566:4566'